apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: hello-python
spec:
  ports:
    - port: 80
      targetPort: 5000
      name: frontend
  selector:
    app: hello-python
  type: LoadBalancer
---
apiVersion: apps/v1beta1  
kind: Deployment
metadata:
  name: frontend
  labels:
    app: hello-python
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: frontend
        image: 'ericdewitte/hello-python:latest'
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: hello-python