apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hello-dc01
  labels:    #### This is added for GSLB
    app: gslb #### This is added for GSLB - Using the selector I chose in the value.yaml
#  annotations:
#    ako.vmware.com/enable-tls: "true"
spec:
  ingressClassName: avi-lb
  rules:
    - host: hello.multi-az.cpod-casden.az-lhr.cloud-garage.net
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: hello-python
              port:
                number: 80
