---
resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.14"

- name: harbor-scan
  type: docker-image
  source:
    repository: warroyo90/harbor-scan-resource
    tag: 1.0.0

resources:
- name: git-repo
  type: git
  source:
    uri: git@github.com:vEDW/hello-python.git
    branch: master
    private_key: {{git-private-key}}

- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: git@github.com:vEDW/hello-python.git
    branch: version
    file: version
    private_key: {{git-private-key}}

- name: hello-python-docker-image
  type: docker-image
  source:
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hello-python-image}}

- name: scan
  type: harbor-scan
  source:
    username: {{harbor_username}}
    password: {{harbor_password}}
    harbor_host: {{harbor_host_url}}
    
- name: cf-dev
  type: cf
  source:
      api: {{cf-api-server}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space-dev}}
      skip_cert_check: false
    
- name: cf-prod
  type: cf
  source:
      api: {{cf-api-server}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space-prod}}
      skip_cert_check: false

- name: kubernetes-aks
  type: kubernetes
  source:
    kubeconfig: {{kubeconfig-aks}}
    namespace: hello-python

jobs:
- name: hello-python-build-docker-image
  public: true
  serial: true
  plan:
  - get: version
    params: {bump: minor}
  - get: git-repo
    trigger: true
  - put: hello-python-docker-image
    params: {build: git-repo,tag_file: version/number,tag_as_latest: true,dockerfile: git-repo/dockerfile}
  - put: version
    params: {file: version/version}

- name: scan-image
  plan:
    - get: git-repo
      passed: [hello-python-build-docker-image]
    - put: scan
      params:
        repository: {{harbor_repository}}
        harbor_scan_thresholds: [{"severity": 4,"count": 10},{"severity": 5,"count": 1}]
        tag: 3.8

- name: deploy-to-cf-dev
  build_logs_to_retain: 30
  plan:
      - get: git-repo
        trigger: true
      - put: cf-dev
        params:
          manifest: git-repo/manifest.yml
          path: git-repo

- name: deploy-to-cf-prod
  build_logs_to_retain: 30
  plan:
      - get: git-repo
        trigger: false
        passed: [deploy-to-cf-dev]
      - put: cf-prod
        params:
          manifest: git-repo/manifest.yml
          path: git-repo

- name: kubernetes-deploy-aks
  plan:
  - get: git-repo
    passed: [hello-python-build-docker-image]
  - get: hello-python-docker-image
    trigger: false

  - put: kubernetes-aks
    params:
      kubectl: apply -f git-repo/k8s/hello-python-deployment.yaml
