---
resources:
- name: git-repo
  type: git
  source:
    uri: git@github.com:vEDW/hello-python.git
    branch: master
    private_key: {{git-private-key}}
    
- name: cf-dev
  type: cf
  source:
      api: {{cf-api-server}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space-dev}}
      skip_cert_check: false
    
- name: cf-prod
  type: cf
  source:
      api: {{cf-api-server}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space-prod}}
      skip_cert_check: false

jobs:
- name: deploy-to-cf-dev
  build_logs_to_retain: 30
  plan:
      - get: git-repo
        trigger: true
      - task: get-current-app-color
        file: git-repo/ci/tasks/current-app-get-info.yml
        params:
          PWS_APP_SUFFIX: {{cf-app-suffix}}
          PWS_API: {{cf-api-server}}
          PWS_ORG: {{cf-org}}
          PWS_USER: {{cf-username}}
          PWS_PWD: {{cf-password}}
          PWS_SPACE: {{cf-space-dev}}
      - task: prepare-app-manifest
        file: git-repo/ci/tasks/app-manifest-prep.yml
        params:
          PWS_APP_SUFFIX: {{cf-app-suffix}}
      - put: cf-dev
        params:
          manifest: app-manifest-output/manifest.yml
          path: git-repo

- name: load-tests
  serial: true
  public: true
  plan:
  - get: git-repo
    trigger: true
    passed:
      - deploy-to-cf-dev
  - task: get-current-app-color
    file: git-repo/ci/tasks/current-app-get-info.yml
    params:
        PWS_APP_SUFFIX: {{cf-app-suffix}}
        PWS_API: {{cf-api-server}}
        PWS_ORG: {{cf-org}}
        PWS_USER: {{cf-username}}
        PWS_PWD: {{cf-password}}
        PWS_SPACE: {{cf-space-dev}}
  - task: run-load-tests
    file: git-repo/ci/tasks/load-tests.yml
    params:
      PWS_APP_SUFFIX: {{cf-app-suffix}}
      PWS_APP_DOMAIN: {{cf-app-domain}}

- name: promote-new-version
  serial: true
  public: true
  plan:
  - get: git-repo
    trigger: true
    passed:
      - load-tests
  - task: get-current-app-color
    file: git-repo/ci/tasks/current-app-get-info.yml
    params:
      PWS_APP_SUFFIX: {{cf-app-suffix}}
      PWS_API: {{cf-api-server}}
      PWS_ORG: {{cf-org}}
      PWS_USER: {{cf-username}}
      PWS_PWD: {{cf-password}}
      PWS_SPACE: {{cf-space-dev}}
  - task: switch-app-routes
    file: git-repo/ci/tasks/update-routes.yml
    params:
      PWS_APP_SUFFIX: {{cf-app-suffix}}
      PWS_API: {{cf-api-server}}
      PWS_ORG: {{cf-org}}
      PWS_USER: {{cf-username}}
      PWS_PWD: {{cf-password}}
      PWS_SPACE: {{cf-space-dev}}
      PWS_APP_DOMAIN: {{cf-app-domain}}

- name: deploy-to-cf-prod
  build_logs_to_retain: 30
  plan:
      - get: git-repo
        trigger: true
        passed:
          - promote-new-version        
      - task: get-current-app-color
        file: git-repo/ci/tasks/current-app-get-info.yml
        params:
          PWS_APP_SUFFIX: {{cf-app-suffix}}
          PWS_API: {{cf-api-server}}
          PWS_ORG: {{cf-org}}
          PWS_USER: {{cf-username}}
          PWS_PWD: {{cf-password}}
          PWS_SPACE: {{cf-space-dev}}
      - task: prepare-app-manifest
        file: git-repo/ci/tasks/app-manifest-prep.yml
        params:
          PWS_APP_SUFFIX: {{cf-app-suffix}}
      - put: cf-prod
        params:
          manifest: app-manifest-output/manifest.yml
          path: git-repo

- name: promote-new-version-to-prod
  serial: true
  public: true
  plan:
  - get: git-repo
    trigger: true
    passed:
      - deploy-to-cf-prod
  - task: get-current-app-color
    file: git-repo/ci/tasks/current-app-get-info.yml
    params:
      PWS_APP_SUFFIX: {{cf-app-suffix-prod}}
      PWS_API: {{cf-api-server}}
      PWS_ORG: {{cf-org}}
      PWS_USER: {{cf-username}}
      PWS_PWD: {{cf-password}}
      PWS_SPACE: {{cf-space-prod}}
  - task: switch-app-routes
    file: git-repo/ci/tasks/update-routes.yml
    params:
      PWS_APP_SUFFIX: {{cf-app-suffix-prod}}
      PWS_API: {{cf-api-server}}
      PWS_ORG: {{cf-org}}
      PWS_USER: {{cf-username}}
      PWS_PWD: {{cf-password}}
      PWS_SPACE: {{cf-space-prod}}
      PWS_APP_DOMAIN: {{cf-app-domain}}