---
resources:
- name: git-repo
  type: git
  source:
    uri: git@github.com:vEDW/hello-python.git
    branch: master
    private_key: {{git-private-key}}
    
- name: cf-dev
  type: cf
  source:
      api: {{cf-api-server}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space-dev}}
      skip_cert_check: false
    
- name: cf-prod
  type: cf
  source:
      api: {{cf-api-server}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space-prod}}
      skip_cert_check: false

jobs:
- name: deploy-to-cf-dev
  build_logs_to_retain: 30
  plan:
      - get: git-repo
        trigger: true
      - put: cf-dev
        params:
          manifest: git-repo/manifest.yml
          path: git-repo

- name: deploy-to-cf-prod
  build_logs_to_retain: 30
  plan:
      - get: git-repo
        trigger: false
      - put: cf-prod
        params:
          manifest: git-repo/manifest.yml
          path: git-repo
